### ISSUE TITLE
Python 3.10 - marimapper PixelBlaze backend runtime error

### ISSUE THREAD

**Issue by kaybee335** [TheMariday/marimapper#57]
For various reasons the "most compatible" version of Python I can install is 3.10.  Some things work but there is a runtime error generated from what seems to be forming the uri for the backend server when running marimapper with the PixelBlaze backend.

marimapper_check_camera functions properly.

```
(venv) [kris@mercury-endeavouros marimapper]$ python --version
Python 3.10.16
```

marimapper(pixelblaze) with no server specified:

```
(venv) [kris@mercury-endeavouros marimapper]$ marimapper --backend PixelBlaze
Process DetectorProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/kris/.local/share/pipx/venvs/marimapper/lib/python3.10/site-packages/marimapper/detector_process.py", line 67, in run
    led_backend = get_backend(self._led_backend_name, self._led_backend_server)
  File "/home/kris/.local/share/pipx/venvs/marimapper/lib/python3.10/site-packages/marimapper/utils.py", line 134, in get_backend
    return pixelblaze_backend.Backend(server)
  File "/home/kris/.local/share/pipx/venvs/marimapper/lib/python3.10/site-packages/marimapper/backends/pixelblaze/pixelblaze_backend.py", line 10, in __init__
    self.pb = pixelblaze.Pixelblaze(pixelblaze_ip)
  File "/home/kris/.local/share/pipx/venvs/marimapper/lib/python3.10/site-packages/pixelblaze/pixelblaze.py", line 259, in __init__
    self._open()
  File "/home/kris/.local/share/pipx/venvs/marimapper/lib/python3.10/site-packages/pixelblaze/pixelblaze.py", line 408, in _open
    uri = "ws://" + self.ipAddress + ":81"
TypeError: can only concatenate str (not "NoneType") to str

```
marimapper(pixelblaze) with --server "IP address"

```
(venv) [kris@mercury-endeavouros marimapper]$ marimapper --backend PixelBlaze --server 192.168.88.113
Process DetectorProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/kris/.local/share/pipx/venvs/marimapper/lib/python3.10/site-packages/marimapper/detector_process.py", line 67, in run
    led_backend = get_backend(self._led_backend_name, self._led_backend_server)
  File "/home/kris/.local/share/pipx/venvs/marimapper/lib/python3.10/site-packages/marimapper/utils.py", line 134, in get_backend
    return pixelblaze_backend.Backend(server)
  File "/home/kris/.local/share/pipx/venvs/marimapper/lib/python3.10/site-packages/marimapper/backends/pixelblaze/pixelblaze_backend.py", line 11, in __init__
    self.pb.setActivePatternByName(
  File "/home/kris/.local/share/pipx/venvs/marimapper/lib/python3.10/site-packages/pixelblaze/pixelblaze.py", line 2363, in setActivePatternByName
    self.setActivePattern(patternId, saveToFlash=saveToFlash)
  File "/home/kris/.local/share/pipx/venvs/marimapper/lib/python3.10/site-packages/pixelblaze/pixelblaze.py", line 1149, in setActivePattern
    if len(patternId) != 17: self.__printDeprecationMessage(self.deprecationReasons.functionalityChanged, "setActivePattern(name_or_id)", "setActivePattern(id)/setActivePatternByName(name")
TypeError: object of type 'NoneType' has no len()

```
marimapper(pixelblaze) with "IP address:port" specified:

```
(venv) [kris@mercury-endeavouros marimapper]$ marimapper --backend PixelBlaze --server 192.168.88.113:80
Process DetectorProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/kris/.local/share/pipx/venvs/marimapper/lib/python3.10/site-packages/marimapper/detector_process.py", line 67, in run
    led_backend = get_backend(self._led_backend_name, self._led_backend_server)
  File "/home/kris/.local/share/pipx/venvs/marimapper/lib/python3.10/site-packages/marimapper/utils.py", line 134, in get_backend
    return pixelblaze_backend.Backend(server)
  File "/home/kris/.local/share/pipx/venvs/marimapper/lib/python3.10/site-packages/marimapper/backends/pixelblaze/pixelblaze_backend.py", line 10, in __init__
    self.pb = pixelblaze.Pixelblaze(pixelblaze_ip)
  File "/home/kris/.local/share/pipx/venvs/marimapper/lib/python3.10/site-packages/pixelblaze/pixelblaze.py", line 259, in __init__
    self._open()
  File "/home/kris/.local/share/pipx/venvs/marimapper/lib/python3.10/site-packages/pixelblaze/pixelblaze.py", line 416, in _open
    self.ws = websocket.create_connection(uri, sockopt=((socket.SOL_SOCKET, socket.SO_REUSEADDR, 1), (socket.IPPROTO_TCP, socket.TCP_NODELAY, 1),))
  File "/home/kris/.local/share/pipx/venvs/marimapper/lib/python3.10/site-packages/websocket/_core.py", line 646, in create_connection
    websock.connect(url, **options)
  File "/home/kris/.local/share/pipx/venvs/marimapper/lib/python3.10/site-packages/websocket/_core.py", line 256, in connect
    self.sock, addrs = connect(
  File "/home/kris/.local/share/pipx/venvs/marimapper/lib/python3.10/site-packages/websocket/_http.py", line 132, in connect
    hostname, port_from_url, resource, is_secure = parse_url(url)
  File "/home/kris/.local/share/pipx/venvs/marimapper/lib/python3.10/site-packages/websocket/_url.py", line 51, in parse_url
    if parsed.port:
  File "/usr/lib/python3.10/urllib/parse.py", line 186, in port
    raise ValueError(f"Port could not be cast to integer value as {port!r}")
ValueError: Port could not be cast to integer value as '80:81'
```

I'm not sure if fixing these issues will just expose a multitude more but am certainly willing to test any possible solutions.

I also have FadeCandy and WLED units that I could resurrect to test those backends with Python 3.10 if that is desirable.

The maintainer of the python 3.11 package on AUR is aware of the current build issue and is looking at it.  It is possible that within the next couple of days this will become a non-issue for me if the package is updated. So there is hopefully another path I can follow should this become a large amount of effort. I will monitor the situation and let you know if a python 3.11 package becomes available and works. You probably don't want to spend too much effort supporting older versions of python.

Thanks very much,
I feel like Don Adams/Get Smart right now: Missed it by *that* much!
I really appreciate your effort with this.

**Comment by TheMariday** [comment]
Quick response,

I think the correct format for this is `marimapper --backend PixelBlaze --server 192.168.88.113`

Have you uploaded the marimapper.epe pattern to your pixelblaze controller via the Pixelblaze editor?

I think what's happening here in scenario 2 is that marimapper is trying to find the "marimapper" effect, however it's not currently loaded.

Not the best error messages in the world and I will put in safeguards now against scenario 1 and 3

**Comment by kaybee335** [comment]
I'll check it out. Will another 
```
pipx install "https://...." 
```
pull the latest or do I have to tell pipx to update instead?

I did not upload the marimapper.eps file to the PixelBlaze. I didn't see that step in the instructions. I'll check that out as well. 

Thanks very much.

**Comment by TheMariday** [comment]
Try uploading the marimapper.epe first and see how that goes.

My pull request doesn't add any fixes so to speak but it does stop you from putting ports in the address field and ensures the default port for pixelblaze is 1.2.3.4

you can test out the new branch with `pipx install git+https://github.com/TheMariday/MariMapper.git@bug/pixelblaze_server --force`

**Comment by kaybee335** [comment]
Thank you. 

I'm just looking for the epe file in my system now. It doesn't seem to be in the venv which is where I expected to find it.

I found it here in the source tree so worst comes to worst, I'll just grab it from GH directly.

**Comment by kaybee335** [comment]
I just cut and pasted the contents of the epe file into the mapper function directly on the PixelBlaze Mapper tab for the device and it's telling me something is wrong with the function.

Is that the right way to load the epe?

Thx

**Comment by TheMariday** [comment]
The epe file is an "effect" that needs to be uploaded to the microcontroller for the mapper to work.

The mapping is separate once the scanning has completed

**Comment by TheMariday** [comment]
My apologies that the documentation is quite thin on the ground here, I don't use pixelblaze myself so googling most of this!

**Comment by TheMariday** [comment]
![image](https://github.com/user-attachments/assets/5e609e21-546f-4d01-9bd1-55e1b5b31de8)
https://electromage.com/docs/user-interface

Ah here we go, see "upload / import patterns from epe files"

**Comment by kaybee335** [comment]
I has just finished doing that (did not update marimapper). I see the pattern is selected on the PixelBlaze so it should be loaded and running.

Unfortunately something happens before the start scan prompt and things freeze although the video window is live. None of the LEDS light up.

Here's the traceback, it seems to have something to do with wayland now?

```
(venv) [kris@mercury-endeavouros marimapper]$ marimapper --backend PixelBlaze --server 192.168.88.113Start scan? [y/n]: [WARNING/DetectorProcess-1] failed to set exposure to -10, your camera might not support exposure control, try darkening the scene and adjusting the threshold with --threshold 
[WARNING/DetectorProcess-1] failed to set exposure to -10, your camera might not support exposure control, try darkening the scene and adjusting the threshold with --threshold 
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/kris/.local/share/pipx/venvs/marimapper/lib/python3.10/site-packages/cv2/qt/plugins"
```

This may be turning into an Arch rabbit hole I'm afraid. Feel free to say "not touching that", I likely would!

**Comment by TheMariday** [comment]
Oh crumbs yea this looks nasty. Could you run it with `-v` just incase there's something going wrong on my end?

**Comment by kaybee335** [comment]
My abject and humblest apologies. 

It did print the Start Scan [Y/n] prompt. It just got lost in all the other cruft.

If I hit Y and enter it does start scanning but them immediately complains about the light level.

I think I'm just dealing with camera issues now. I'll either wait until it gets darker or borrow a newer webcam from a neighbour.

Thanks very much for the prompt feedback. I'll report back later this evening and hopefully the issue can be closed.

PS - I'm new to the PixelBlaze so also apologise for leading you down the epe confusion trail.

**Comment by TheMariday** [comment]
Absolutely no need for apologies! Thank you so much for the feedback, honestly it's just nice to know people are using the tool :D

**Comment by kaybee335** [comment]
Well it mapped. It took 70 scans to display a single connected string in the feedback window. I think the camera was too close to the tree and there were lens distortion effects in play. It had significant trouble with the top and bottom of the tree. I'll try again later when I don't have to be so close to ensure darkness.

My problem now is that I have a final CSV file and no idea what to do with it.  The PixelBlaze mapper tab seems to want either JSON or JavaScript for map definitions. I don't see any file in my marimapper run directory that seems suited to the PixelBlaze.  Just a whole bunch of CSV files.

Is the PixelBlaze backend supposed to create files other than the CSVs?

I've done web searches and I'm not finding anything about defining maps with CSV files.

Any suggestions?

**Comment by TheMariday** [comment]
There are steps in the readme that show how to upload it to pixelblaze.

>Once you've completed your 3D map, upload it to pixelblaze using marimapper_upload_to_pixelblaze --help

Also 70 scans? That's definitely not right! it should produce a valid reconstruction with just 2 scans!

**Comment by TheMariday** [comment]
Could you share your scan CSV files with me please so I can see what's going wrong?

**Comment by kaybee335** [comment]
Warning: Long and contains much speculation

1. Documentation

*jumps on soapbox*

Documentation should never be hidden by default.  Until your last message I had zero idea that there was information in the README.md on the individual backends. Why? Because the list of backends looks just like a list.  Not an active expandable piece of documentation.  Which I don't really expect in 'static' Markdown. So I missed it entirely until you told me explicitly that it was there and went on a deliberate hunt, even after reading the doc at least six times from top to bottom prior.

I can understand not wanting to clutter the README but I would much rather scroll past information than miss it entirely. As an alternative you could  provide the details for the individual backends at the end of the README and direct the reader to go look there for their particular backend.

*jumps off soapbox*

2. LED Detection

LEDs were being detected just fine. I had to mess with the --threshold a bit but was getting nice clean detections (more on this later).

3. CSV files

Sure.  Which do you want? I have a final 3D scan that worked where I discarded all of the intermediate 2D scans and also a 3D that didn't work with all of the 2D scans.  Happy to tgz them and send to you. 

4. Speculation Land

Background Info

Tree:
- very small (<1m) but extremely dense near the trunk
- tree was washed before stringing the lights (silly, but relevant)
- 100 'fairy' neopixels strung in the tree
  - the 'fairy' neopixels transmit light outwards as expected but also somewhat along the plastic sheathing between LEDs
  - the lights are strung with the lowest numbered pixel at the top of the tree and the highest at the bottom
 
Camera
- no auto-exposure!!
- external webcam mounted on tripod during scanning

Lighting Conditions
- varying
  - large number of scans required so much time to complete that lighting changed during the scan (both natural and artificial)

What I think went wrong (in order of level of effect)

a) No auto-exposure.  

This put me behind the eight ball from the very start. I had to adjust the --threshold parameter so high for clean detection without detecting:
- self-generated (from the pattern) reflections off of the tree itself (remember someone deciding that washing it was a good idea?)
- the diffusion of light along the string 
- self generated reflections from *any* reflective surface within the camera view exterior to the tree

The end result of this was that the threshold was set so high that the scanner did not detect LEDs 'through' the tree. This just required more scans to get more of the tree in view.  Without rotating the tree too much and losing registration between scans. So lots of scans just to get all of the LEDs detected in the first place.  Auto-exposure would have helped considerably here.

b) So many scans took so much time that some lighting 'event' is almost guaranteed to happen mid-scan

I think I had everything go wrong here that was physically possible.  I had home automation all of a sudden turning the lights on in my nicely darkened room, I had the same automation decide to turn on some tiny device that was in the camera view but not my view.  That device had a power LED that was happily slurped into the scan and would not go away despite marimapper not being able to control it. Each time that (or similar) happened the scan had to be aborted because the mapper would accept the static LED from then on and try to connect the 'string' to it. I had reflections appear where they weren't before because of natural light levels. It goes on.

c) there are a lot of lights in the tree and the tree is very dense.  Some of the LEDs are buried down near the trunk where they are quite obscured by intervening branches.  They are only visible from a narrow angle of view but often visible from multiple points of view because they are so close to the trunk.

This is what seemed to really prevent the mapper from connecting the strings.  It would decide it had found a LED, then a very small rotation would cause it to disappear.  Then a couple of scans later it would show up from another point of view. And then disappear again. Then the mapper would decide it hadn't really found it at all and previously connected stuff would be exploded into multiple small unconnected segments.

d) the tree was mapped upside down (tip at y=0, base at y=1).

I'm pretty sure this is the result of my stringing the lights with the string starting at the top of the tree.  Although I have no idea why this should matter to the mapper. Unless the lowest numbered LED is regarded as a 'base reference' somehow. I still don't understand why this would result in an upside down tree rather than a translated tree.

The map worked when it was uploaded but any bottom->top patterns went top->bottom instead. Left->right were also switched as expected with the map. I can fix this in the CSV file by just replacing the Y values with (1-Y) to do the flip around Y=0.5 so not really a problem.

Unless it was somehow confusing the scanning process. This I have no insight into so I'll leave you to think about that.

Conclusions

- I am my own worst enemy.  No about about that.
- Most of my problems would not have occurred if:
  - camera had auto-exposure
  - better control of lighting both natural and artificial (need a dark room with no reflective surfaces)
  - LEDs on strings weren't buried deep within tree
  - tree wasn't so dense causing many obscurations

Recommendations
- please change the documentation so that the backend detail is more 'in your face'.  Most people are going to want backend info of some type. Very few will be writing their own backends (I suspect) and that information isn't hidden at all. I don't understand the priorities here in making this choice. It is not very user friendly in my opinion.
*finally kicks soapbox away for good*
- there may be value in implementing some sort of 'sanity check' into the mapper if a large number of scans seem to be required (>5?).  I would think the mapper would have some idea of a bounding volume by that time and could start to examine LED positioning based on where it is in relation to that volume.  If a LED is detected/positioned outside that volume  (to some tolerance) when the scan has completed, the mapper could try and turn that LED on and off to confirm that it did have control of what it detected before repositioning for the next scan. I think this would stop the mapper from accepting static LEDs that turn on during the scan process as things to be incorporated. Which causes 'model explosion' in my case.
- better indication of when the scan has a complete string with all detected LEDs connected linearly with no loops. The only way I could tell if i was 'done' was by closely examining the map and verifying the above by rotating, etc.  
- On a related note, what is the significance of the colours assigned to the detected LEDs by the mapper window? Black seems to indicate some degree of 'non-connectedness' but I have no idea about the other colours. I suspect it might be useful to know.

I think that is the majority of it, My conclusion is that the large number of scans wasn't the fault of the mapper although you will have a much better idea. I think most of my wounds were self-inflicted on this.

Anyway, hopefully there's some useful information in here for you.

Let me know about the CSVs and anything else you would like further clarified (although given the length of this response I could understand your hesitation in asking!)

Thanks!

**Comment by kaybee335** [comment]
I've been thinking a bit about the 'bounding volume' idea and realised that you likely don't have control of individual pixels, only the ability to start a pattern running.

I'm guilty of premature optimisation. I was trying to avoid prompting for another complete scan from the same location should tolerance be exceeded. In that case, the user should also likely be prompted to check the view from the cameras viewpoint for new light sources or (new) sources of reflection outside the volume.

**Comment by kaybee335** [comment]
On another thought, does the mapper only check for the presence of light or does it look for the presence and then the following absence of light (after some number of frames)?

**Comment by TheMariday** [comment]
Hi @kaybee335, thank you so much for the thorough feedback! I really appreciate it!

It does sound like you've put marimapper through the worst possible conditions so good to find where it's breaking point is!

I am in agreement with your points but lets go through those points and see what we can do

## Documentation on backends

I totally understand the frustration in finding the documentation here, it is something I overlooked and will address.

My current thought is to change it from a drop-down to a hyperlink to another readme which will allow as much details as is required depending on the backend.

## Exposure control

Not many people have been able to get successful scans without exposure control due to similar issues that you've faced.

This has sadly got to a point where I will have to change the documentation and operation of Marimapper so cameras without these controls are explicitly not supported.

## Safeguards & Sanity checks

I have been adding safeguards to marimapper, however I have to be very careful as we don't have any priors to estimate what we're supposed to be looking at.

For example, I know marimapper has been used to map things from nixie tubes to led lights wrapped around a house.

I am very cautious about adding any safeguards that might cause issues with layouts that it might deem as "incorrect"

It's also just really hard to put these checks in place and have found there to be more benefit on focusing on getting good input data compared to filtering bad output data.

## LED Colours

Older versions of marimapper had a rainbow colour scheme by default which had a few issues, mainly that the bounding box for the visualiser could only be initialised once so the rainbow range would only extend to the first set of detected leds, and the rest would be black. Easy way to test this is to just close and re-open marimapper.

In the latest version of Marimapper (2.3.1), the colour scheme has been changed and leds shouldn't appear as black.
If they do, it might be a rendering issue with open3d.

For your reference, the new color scheme should be:
- Green: detected
- Blue: interpolated or merged (i.e. we have a rough idea of where it is but not 100% certain)

## Other QA:
So the detector does turn on and off individual LEDs!
The process is to turn off all leds, ensure that no leds are detected, turning on the required led, waiting for detection, then repeat.

When it comes to orientation, it uses the orientation of the first cameras pose which is defined with Y- being down.

I understand that most people would want Y+ being up so I will change this.

## CSV's, custom backends, project scope and personal notes

Firstly, I never expected this tool to get any traction at all outside of the Electronic Fursuit community so firstly thank you for checking it out!

After asking my intended users how they'd like the backends to operate, writing their own was actually the overwhelming response, as we very rarely use off the shelf systems.

WLED and PixelBlaze integration was never originally planned and all done by the  wonderful @TGCFabian and @savdb.

The upshot of this is I have never even used a pixelblaze or a wled, so I am struggling at supporting people at the moment as I didn't expect so many people to use pre-built backends at all!

I am actively looking for people to support in future developments which require adjustments to these backends.

## Plan:

Docs:
- [ ] Add more documentation surrounding how you should lay out your scene (i.e. tape up power leds etc)
- [ ] Break out Backend documentation and make it more obvious
- [ ] Add led colour documentation

Code:
- [ ] Add a "percentage complete" notice to show how many leds you've reconstructed
- [ ] Investigate upside-down (inverted y)
- [ ] Disable support of cameras without exposure control

I hope this answers at least some of your questions and thank you again for the feedback!
P.S. CSV wise, zip them all up please and send them over! I can go through the data manually and see if there are any issues that jump out that we've missed.

**Comment by kaybee335** [comment]
So. My response to "too fancy" Markdown in the docs is fancy Markdown in your response?

**Well played, well played!** 

### Documentation on backends

I agree completely.  I did actually check the backends and backends/pixelblaze directories for additional README's. That would be a great way to organise them with hyperlink access from the main doc.

### Exposure control

Agree here as well. It's only because I could figure out the root cause that I persisted. I knew I could eventually bend it to my will once I understood what was confusing it.

If you are going to do this, I would suggest providing a list of cameras known to have exposure control that works with marimapper/OpenCV.  I did some searching and this doesn't seem to be easily find-able information. At least not in a nice clear summary form.

An appeal to the (now much larger) marimapper community would provide a good starting point I suspect.

### Safeguards & Sanity checks

Gotcha completely here. I used to work in video surveillance and video target detection (both outside) so know how unpredictable things can be. Managing detection vs false alarms is something that has to be fitted to intended use.

I'm not at all surprised that my suggestion may conflict with some of your other known use cases.

### LED Colours

New suggestion: modify marimapper so that this doesn't happen. :-)

```
(venv) [kris@mercury-endeavouros marimapper]$ marimapper --version
usage: marimapper [-h] [--device DEVICE] [--exposure EXPOSURE] [--threshold [0-255]] [--backend BACKEND]
                  [--start START] [--end END] [--server SERVER] [-v] [--max_fill MAX_FILL]
                  [--disable_movement_check]
                  [dir]
marimapper: error: unrecognized arguments: --version
```
I'll update my version and give it a try. I'm **not** trying this in daylight again though! :-)

### Other QA:

Sounds good. Your call to make based on your user knowledge. I can easily flip it in the CSV file as I mentioned.

Might be worth mentioning in the docs that this may happen after making certain dumb wiring decisions.

### CSV's, custom backends, project scope and personal notes

Congratulations on your success!! I guess? :-)

You attracted the attention of the maker neopixel community and they're big, active and fascinated by shiny things! I will now be checking out the Electronic Fursuit community as it seems like it's a fascinating place!

I am amazed that you have gotten as far as you have without having those devices. The PixelBlaze is extremely popular in the maker neopixel community now so you are definitely riding the popularity of it now that people know.  In my case you can credit/blame GeekMomProjects and JasonCoon over in the Fediverse.

I'm happy to do what I can to help support. I'm a novice to the PixelBlaze as well but actually have a few. As you may have noticed, I tend to question things so would be happy to add any future discoveries to the docs via pull request or however you prefer. 

As a first thought, I could put out an appeal to my followers on Mastodon for cameras that are known to have working exposure control with marimapper/OpenCV. That's independent of anything that you are doing on the mapper so wouldn't 'get in the way'.  I'm also sure that my followers would be happy to boost a request such as this which is trying to better the community. I'm no great influencer by any means but all it takes is a kick start. I'll collate the list and provide it to you as a Markdown doc so it can be added to the repo for other people to contribute later.

### Plan

Everything sounds good to me. If you would like doc review (or contribution) just let me know.

You covered everything.

I'll get the CSVs to you later today.

Congratulations! You have created a great tool solving a really hard problem. Not an easy thing to do at all. 

Definitely pats on the back (or tail base sckritches if preferred) are deserving!

**Comment by kaybee335** [comment]
The CSV files are attached (hopefully).

Thanks.

[kaybee335-tree.zip](https://github.com/user-attachments/files/18283702/kaybee335-tree.zip)

**Comment by kaybee335** [comment]
One (hopefully last) thought. 

Maybe it isn't the best idea to ban no-exposure control cameras entirely. How about an argument to the mapper like -override_ae and then print a warning of the perils. A statement that tells the user they better know what they're doing if selecting this as they are making the mappers job much harder. Then confirmation (maybe full 'yes') before proceeding.

That wouldn't lock out people who are willing to keep trying. Not thinking of anyone in particular of course. 😉

Thanks again and Happy New Year!

**Comment by TheMariday** [comment]
Hi Kaybee

I've done some work today at addressing some of your concerns and would love your thoughts even just on the documentation!

You can find the pull request linked to this issue and would love any comments especially surrounding documentation of the PixelBlaze workflow.

I //think// I've addressed everything you've raised best I can.

Only thing I ran into that caused issue is that the visualiesr camera now starts pointing the wrong way. Just means you need to turn it around to see the scan from the "front"

I've added some sanity checks to help with some basic, but not a huge amount there.

led colors have been updated as well so will default to the regular green / blue colorscheme

Also the list of cameras idea, you're gonna hate me, this was already in the README, in a dropdown.

I have now removed all dropdowns :D 

I have decided to drop support  for cameras with no exposure control and have added in an obnoxiously long command line flag to disable it if you really really have to.

Happy new year and thank you again for your feedback.

**Comment by kaybee335** [comment]
That's awesome. I'll take a look tomorrow (hopefully morning).

Hopefully you can close this one tomorrow for good. It has spawned too many things. It can't be allowed to continue existing! 

Thanks very much for all your effort on this!

And you gave me the best laugh of 2025 (almost coffee spout worthy) when you revealed where the camera list was. Of course, where else would something I can't find be? 😂

**Comment by kaybee335** [comment]
I got caught up in things again today but I did have a chance to go through the doc changes. 

The links to the backend docs don't work in the branch because main is hardcoded in the path and they don't exist there. This could cause trouble for reviewers in the future when they are there and they will link to an old version of the document. Can the paths be made relative? Or the branch name somehow substituted into the include?

It's not a problem now but I think it will likely bite in the future. 

Other than that, nothing of significance. I also read through the changes as you describe them and they all make sense.

I'd recommend closure of the issue and go ahead with the release. I'll just raise new issues if necessary. That will be much easier to track anyway. 

Thanks again!

**Comment by TheMariday** [comment]
Hi @kaybee335.

I've now released v2.4 which has the changes in!

Let me know how you get on if you come back to this but no problem if not.

I'll leave this issue closed and we can raise new issues if anything occurs.

Thank you so so much for your detailed feedback, it genuinely means a lot to me.

Only last thing to add is that I'm currently working on implementing a mode which allows cameras to be used that don't support exposure control. This should make things a lot easier and removes the pressure for people to use "supported cameras". And it should run on mac! Because of this i have reverted the error / quit messages.

Anyway, Thank you again and I hope that this tool gets only better for you!
